### ISSUE TITLE
__fzf_install has a syntax error

### ISSUE THREAD

**Issue by rayonix** [fisherman/fzf#26]
When running `fisher update` the following error is outputted:
``` fish
➤ fisher up
OK fisherman is up to date
Updating 24 plugins
OK Latest docker-completion
OK Latest done
OK Latest debug
OK Latest docker-compose
OK Latest cprintf
OK Latest errno
OK Latest await
OK Latest hash
OK Latest archlinux
OK Latest title
OK Latest paths
OK Latest bass
OK Latest gi
OK Latest logger
OK Latest technicolor
OK Latest get
OK Latest string
OK Latest segment
OK Latest last_job_id
OK Latest shark
OK Latest fishtape
OK Latest getopts
OK Latest z
OK Latest fzf
$` is not a valid variable in fish.
~/.config/fish/functions/__fzf_install.fish (line 3):         get --prompt "Where would you like to install it? (default \"$HOME/.fzf\")\n->" --default "$HOME/.fzf" -r "\([^\0 !$`&*()+]\|\\\(\ |\!|\$|\`|\&|\*|\(|\)|\+\)\)\+" | read -l install_dir
                                                                                                                                                                                  ^
from sourcing file ~/.config/fish/functions/__fzf_install.fish
	called on line 765 of file ~/.config/fish/functions/fisher.fish

in function “__fisher_plugin_enable”
	called on line 637 of file ~/.config/fish/functions/fisher.fish
	with parameter list “/GlobalHome/steve/.config/fisherman/fzf”

in function “__fisher_update”
	called on line 255 of file ~/.config/fish/functions/fisher.fish
	with parameter list “archlinux await bass cprintf debug docker-completion docker-compose done errno fishtape fzf get getopts gi hash last_job_id logger paths segment shark string technicolor title z”

in function “fisher”
	called on standard input
	with parameter list “up”

Done in 5s 45ms
```

Also I do have fzf installed so this code shouldn't be executed in my case. I guess the interpreter still parses it?

**Comment by jethrokuan** [comment]
Hi, what fish version are you running? I think regex had some changes in
fish 2.4.0.

On 29 Dec 2016 2:22 AM, "rayonix" <notifications@github.com> wrote:

When running fisher update the following error is outputted:

➤ fisher up
OK fisherman is up to date
Updating 24 plugins
OK Latest docker-completion
OK Latest done
OK Latest debug
OK Latest docker-compose
OK Latest cprintf
OK Latest errno
OK Latest await
OK Latest hash
OK Latest archlinux
OK Latest title
OK Latest paths
OK Latest bass
OK Latest gi
OK Latest logger
OK Latest technicolor
OK Latest get
OK Latest string
OK Latest segment
OK Latest last_job_id
OK Latest shark
OK Latest fishtape
OK Latest getopts
OK Latest z
OK Latest fzf
$` is not a valid variable in fish.
~/.config/fish/functions/__fzf_install.fish (line 3):         get
--prompt "Where would you like to install it? (default
\"$HOME/.fzf\")\n->" --default "$HOME/.fzf" -r "\([^\0
!$`&*()+]\|\\\(\ |\!|\$|\`|\&|\*|\(|\)|\+\)\)\+" | read -l install_dir


                                    ^
from sourcing file ~/.config/fish/functions/__fzf_install.fish
	called on line 765 of file ~/.config/fish/functions/fisher.fish
in function “__fisher_plugin_enable”
	called on line 637 of file ~/.config/fish/functions/fisher.fish
	with parameter list “/GlobalHome/steve/.config/fisherman/fzf”
in function “__fisher_update”
	called on line 255 of file ~/.config/fish/functions/fisher.fish
	with parameter list “archlinux await bass cprintf debug
docker-completion docker-compose done errno fishtape fzf get getopts
gi hash last_job_id logger paths segment shark string technicolor
title z”
in function “fisher”
	called on standard input
	with parameter list “up”

Done in 5s 45ms

Also I do have fzf installed so this code shouldn't be executed in my case.
I guess the interpreter still parses it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fisherman/fzf/issues/26>, or mute the thread

**Comment by tasuten** [comment]
Hello, I encountered the same problem, in fish **2.4.0**, on macOS sierra.
I installed fish from Homebrew.

```
$ fish -v 
fish, version 2.4.0
$ fish -n .config/fisherman/fzf/functions/__fzf_install.fish
$` is not a valid variable in fish.
.config/fisherman/fzf/functions/__fzf_install.fish (line 3):         get --prompt "Where would you like to install it? (default \"$HOME/.fzf\")\n->" --default "$HOME/.fzf" -r "\([^\0 !$`&*()+]\|\\\(\ |\!|\$|\`|\&|\*|\(|\)|\+\)\)\+" | read -l install_dir
                                                                                                                                                                                         ^
<W> fish: Error while reading file .config/fisherman/fzf/functions/__fzf_install.fish
```

And I tried to build fish 2.3.0 and 2.3.1 from source (`./configure; and make`), and to execute, but same problem occured too.
```
$ fish-2.3.0/fish -v 
fish, version 2.3.0
$ fish-2.3.0/fish -n ~/.config/fisherman/fzf/functions/__fzf_install.fish
$` is not a valid variable in fish.
~/.config/fisherman/fzf/functions/__fzf_install.fish (line 3):         get --prompt "Where would you like to install it? (default \"$HOME/.fzf\")\n->" --default "$HOME/.fzf" -r "\([^\0 !$`&*()+]\|\\\(\ |\!|\$|\`|\&|\*|\(|\)|\+\)\)\+" | read -l install_dir
                                                                                                                                                                                           ^
fish: Error while reading file
/Users/xxxxx/.config/fisherman/fzf/functions/__fzf_install.fish
```

```
$ fish-2.3.1/fish -v
fish, version 2.3.1
$ fish-2.3.1/fish -n ~/.config/fisherman/fzf/functions/__fzf_install.fish
$` is not a valid variable in fish.
~/.config/fisherman/fzf/functions/__fzf_install.fish (line 3):         get --prompt "Where would you like to install it? (default \"$HOME/.fzf\")\n->" --default "$HOME/.fzf" -r "\([^\0 !$`&*()+]\|\\\(\ |\!|\$|\`|\&|\*|\(|\)|\+\)\)\+" | read -l install_dir
                                                                                                                                                                                           ^
fish: Error while reading file
/Users/xxxxx/.config/fisherman/fzf/functions/__fzf_install.fish
```

I think that using `'`  instead of `"` can solve the problem.

**Comment by jethrokuan** [comment]
@tasuten thanks for all the testing. It turns out I didn't update my symlinks before testing out the script, which led it to incorrectly pass on my machine. Pushed the fix up, should be working now.

**Comment by rayonix** [comment]
@tasuten thanks for the doing the testing. @jethrokuan thanks for fixing this so quickly.
