### ISSUE TITLE
Fish 2.6: Command substitutions now have access to the terminal

### ISSUE THREAD

**Issue by domoritz** [fisherman/fzf#42]
What are the implications of https://github.com/fish-shell/fish-shell/issues/1362 and https://github.com/fish-shell/fish-shell/pull/3922 for this extension?

**Comment by jethrokuan** [comment]
Honestly? no clue.

I don't fully understand its implications, but afaik nothing done in this plugin waits for user input other than calling `fzf`, which is done via `fish -c` and not command substitutions.

**Comment by therealpxc** [comment]
It was an upstream issue, but it looks like they [switched](https://github.com/junegunn/fzf/commit/0508e70f9bf941e3429668fcef955919a71e03c2#diff-8d62cdf37bacdb5aadde5daf0e91cecf) to a different method anyway.

I don't know that the bug affects this plugin, either, since I think by now this implementation is totally different. I think this change in Fish 2.6.0 just gives more options for implementing fzf integration using subshells if anyone should so choose.

**Comment by therealpxc** [comment]
Oh; I just took a second look:

Answer: this doesn't affect keybinds behavior, but it makes, e.g. `vim (fzf)` work properly, which is quite nice.

**Comment by jethrokuan** [comment]
Yup seems this dosen't affect the plugins. I'll keep tabs on development in the original repo. As far as possible I don't want to diverge too far from it; just want to keep the functionality around while having goodies such as lazy loading functions, and more appropriate customizations.
