### ISSUE TITLE
auto install fzf bin

### ISSUE THREAD

**Issue by gozes** [fisherman/fzf#5]
given that this plugin depends on binary that has zero dependencies then I think the plugin should ether install the binary automatically or ask at install time or first run to download the binary. this is specially useful now that there is a fisherfile because if you keep your fish config under git, like I do, then you can just pull your config on a new system and run fisher and be back to your usual setup.

**Comment by jethrokuan** [comment]
fisherman doesn't have the concept of a pre/post install script, otherwise this would be a good idea. I'd have to run checks in `conf.d` , and that adds to shell startup time.

The installation procedure of fzf is also different for different OSes. Some may choose to use `go get`, some may get it using `brew` or whatever package managers they are using. The recommended git method of installation is also not straightforward, because it reads from stdin during the installation process.

If you have any ideas on how to implement this, let me know!

**Comment by jethrokuan** [comment]
I realized the check didn't have to avoid shell startup time.

I'll come up with something.

**Comment by jethrokuan** [comment]
@gozes https://github.com/fisherman/fzf/commit/49dd90a5f4da421e87c2c5f59b8ee12558d48068 has this functionality, but it's really hackish. I'm doing dirty things to shush the default install script that comes with the fzf git repo.

I realize that one can simply rewrite the install script to specifically suit fish users, but I haven't got the time. You can tackle this if you feel like it, perhaps I will at a later point in time if nothing has been done about it.

Would be great if you could do some testing.

**Comment by gozes** [comment]
I'll test it when I get back home

**Comment by jethrokuan** [comment]
Installer is rewritten completely, should work, if it doesn't let me know

**Comment by gozes** [comment]
it seams to be workings but I already hand the binary install

**Comment by jethrokuan** [comment]
If you had the binary install then it should bypass the installation process, so that's a good thing.

**Comment by jethrokuan** [comment]
I'll close this as fixed.
